// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fes-concepts/BottomTabs.tsx": () => import("../components/mockups/fes-concepts/BottomTabs.tsx"),
  "./components/mockups/fes-concepts/Dashboard.tsx": () => import("../components/mockups/fes-concepts/Dashboard.tsx"),
  "./components/mockups/fes-concepts/EditorialCards.tsx": () => import("../components/mockups/fes-concepts/EditorialCards.tsx"),
  "./components/mockups/fes-concepts/SearchFirst.tsx": () => import("../components/mockups/fes-concepts/SearchFirst.tsx"),
  "./components/mockups/fes-menu/GlassDepth.tsx": () => import("../components/mockups/fes-menu/GlassDepth.tsx"),
  "./components/mockups/fes-menu/LayeredMaterial.tsx": () => import("../components/mockups/fes-menu/LayeredMaterial.tsx"),
  "./components/mockups/fes-nav/BottomSheet.tsx": () => import("../components/mockups/fes-nav/BottomSheet.tsx"),
  "./components/mockups/fes-nav/FrostedAtmospheric.tsx": () => import("../components/mockups/fes-nav/FrostedAtmospheric.tsx"),
  "./components/mockups/fes-nav/SideDrawer.tsx": () => import("../components/mockups/fes-nav/SideDrawer.tsx"),
  "./components/mockups/fes-nav/TileGrid.tsx": () => import("../components/mockups/fes-nav/TileGrid.tsx")
};
